language: python

python:
  - "3.6"

install:
  - pip install -e .
  - pip install pytest-mock  
  - pip install pytest-cov codecov # Install packages for code coverage report

script:
  - pytest --cov=src test # Point to the source directory

after_success:
  - codecov 

